# Generated by Django 5.1.7 on 2025-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('genre', models.CharField(choices=[('FICTION', 'Fiction'), ('FANTASY', 'Fantasy'), ('SCI_FI', 'Science Fiction'), ('MYSTERY', 'Mystery & Thriller'), ('ROMANCE', 'Romance'), ('HORROR', 'Horror'), ('HISTORICAL', 'Historical Fiction'), ('ADVENTURE', 'Adventure'), ('DYSTOPIAN', 'Dystopian'), ('CONTEMPORARY', 'Contemporary'), ('CLASSIC', 'Classic Literature'), ('GRAPHIC_NOVEL', 'Graphic Novel'), ('SHORT_STORIES', 'Short Stories'), ('POETRY', 'Poetry'), ('YOUNG_ADULT', 'Young Adult'), ('CHILDRENS', 'Children’s Books'), ('NON_FICTION', 'Non-Fiction'), ('BIOGRAPHY', 'Biography & Memoir'), ('SELF_HELP', 'Self-Help'), ('BUSINESS', 'Business & Finance'), ('SCIENCE', 'Science & Technology'), ('HISTORY', 'History'), ('PHILOSOPHY', 'Philosophy'), ('RELIGION', 'Religion & Spirituality')], max_length=20)),
                ('author', models.CharField(max_length=25)),
            ],
        ),
    ]
